import Head from 'next/head'
import Image from 'next/image'
import SectionMenu from '@/components/main/SectionMenu'
import SectionEvents from '@/components/main/SectionEvents'
import Landing from '@/components/main/Landing'
import SectionAbaout from '@/components/main/SectionAbaout'
import Footer from '@/components/main/Footer'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Landing></Landing>
      <SectionMenu></SectionMenu>
      <SectionEvents></SectionEvents>
      <SectionAbaout></SectionAbaout>
      <Footer></Footer>

    </>
  )
}

